version: '3'

services:
  database:
    container_name: database
    image: ghcr.io/baosystems/postgis:15-3.3
    volumes:
      - ./data/database:/var/lib/postgresql/data
    networks:
      - directus
    environment:
      POSTGRES_USER: 'directus'
      POSTGRES_PASSWORD: 'directus'
      POSTGRES_DB: 'directus'

  cache:
    container_name: cache
    image: redis:7
    ports:
      - 6379:6379
    networks:
      - directus

  directus:
    container_name: directus
    build:
      context: .
    image: ghcr.io/floatingpoints/backend:main
    ports:
      - 8055:8055
    volumes:
      # By default, uploads are stored in /directus/uploads
      # Always make sure your volumes matches the storage root when using
      # local driver
      - ./uploads:/directus/uploads
      # Make sure to also mount the volume when using SQLite
      # - ./database:/directus/database
      # If you want to load extensions from the host
      # - ./extensions:/directus/extensions

      # Database snapshot
      - ./snapshots:/directus/snapshots
    networks:
      - directus
    depends_on:
      - cache
      - database
    env_file:
      - .env.local

networks:
  directus:
